//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCLEAN
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class MoguciPosao : INotifyProperyChanged
    {
        public string ulica { get; set; }
        public Nullable<double> povrsina { get; set; }
        public string planp { get; set; }
        public string tip { get; set; }

        private bool _stiklirano;
        public bool Stiklirano
        {
            get => _stiklirano;
            set
            {
                _stiklirano = value;
                if (PropertyChanged != null)
                    PropertyChanged(this, new PropertyChangedEventArgs("Stiklirano"));
            }
        }
        public MoguciPosao(bool s)
        {
            Stiklirano = s;
        }
        public MoguciPosao() { }

        public event PropertyChangedEventHandler PropertyChanged;
    }
}
