//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCLEAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posao
    {
        public int idPosla { get; set; }
        public string tip { get; set; }
        public System.TimeSpan vreme { get; set; }
        public string ulicaIme { get; set; }
        public System.DateTime datum { get; set; }
        public string userRadnika { get; set; }
    
        public virtual Nalog Nalog { get; set; }
        public virtual Ulica Ulica { get; set; }
    }
}
